import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import { Platform } from "react-native";
import { askBudgetlyAI } from "./aiService";
import { calculateFinancialHealthScore } from "./healthScoreService";
import { getTransactions } from "./transactionService";

function formatCurrency(amount: number) {
  return `$${amount.toFixed(2)}`;
}

function escapeHtml(text: string) {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/\n/g, "<br />");
}

export async function generateMonthlyPDFReport() {
  const transactions = await getTransactions();

  const income = transactions
    .filter((t) => t.type === "income")
    .reduce((sum, t) => sum + Number(t.amount), 0);

  const expenses = transactions
    .filter((t) => t.type === "expense")
    .reduce((sum, t) => sum + Number(t.amount), 0);

  const balance = income - expenses;
  const savingsRate = income > 0 ? ((income - expenses) / income) * 100 : 0;
  const healthScore = calculateFinancialHealthScore(transactions);

  const spendingByCategory = transactions
    .filter((t) => t.type === "expense")
    .reduce<Record<string, number>>((acc, t) => {
      acc[t.category] = (acc[t.category] || 0) + Number(t.amount);
      return acc;
    }, {});

  const topCategories = Object.entries(spendingByCategory)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 5);

  const recentTransactions = transactions.slice(0, 8);

  const aiReport = await askBudgetlyAI(
    "Generate a polished monthly financial report with overview, top spending categories, financial health, and recommendations."
  );

  const categoryRows =
    topCategories.length > 0
      ? topCategories
          .map(
            ([category, amount]) => `
              <tr>
                <td>${category}</td>
                <td style="text-align:right;">${formatCurrency(amount)}</td>
              </tr>
            `
          )
          .join("")
      : `<tr><td colspan="2">No expense categories yet.</td></tr>`;

  const transactionRows =
    recentTransactions.length > 0
      ? recentTransactions
          .map(
            (t) => `
              <tr>
                <td>${t.description || t.category}</td>
                <td>${t.category}</td>
                <td>${t.type}</td>
                <td style="text-align:right;">${formatCurrency(Number(t.amount))}</td>
              </tr>
            `
          )
          .join("")
      : `<tr><td colspan="4">No transactions yet.</td></tr>`;

  const html = `
    <html>
      <body>
        <style>
          body {
            font-family: Arial, sans-serif;
            padding: 32px;
            color: #111827;
          }

          .header {
            background: #171A2F;
            color: white;
            padding: 28px;
            border-radius: 24px;
          }

          .brand {
            font-size: 28px;
            font-weight: 800;
            margin-bottom: 6px;
          }

          .subtitle {
            color: #C7CBDD;
            font-size: 14px;
          }

          .grid {
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            gap: 14px;
            margin-top: 24px;
          }

          .card {
            background: #F4F6FB;
            border-radius: 18px;
            padding: 18px;
          }

          .label {
            color: #6B7280;
            font-size: 12px;
            font-weight: 700;
            text-transform: uppercase;
            letter-spacing: 0.6px;
          }

          .value {
            font-size: 24px;
            font-weight: 800;
            margin-top: 8px;
          }

          h2 {
            margin-top: 32px;
            font-size: 20px;
          }

          table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 12px;
          }

          th {
            text-align: left;
            color: #6B7280;
            font-size: 12px;
            text-transform: uppercase;
            padding-bottom: 8px;
            border-bottom: 1px solid #E5E7EB;
          }

          td {
            padding: 10px 0;
            border-bottom: 1px solid #EEF0F5;
          }

          .analysis {
            background: #F4F6FB;
            border-radius: 18px;
            padding: 20px;
            line-height: 1.6;
            margin-top: 12px;
          }

          .footer {
            margin-top: 36px;
            color: #6B7280;
            font-size: 12px;
            text-align: center;
          }
        </style>

        <div class="header">
          <div class="brand">Budgetly Monthly Report</div>
          <div class="subtitle">Generated by Penny, your personal finance coach</div>
        </div>

        <div class="grid">
          <div class="card">
            <div class="label">Income</div>
            <div class="value">${formatCurrency(income)}</div>
          </div>

          <div class="card">
            <div class="label">Expenses</div>
            <div class="value">${formatCurrency(expenses)}</div>
          </div>

          <div class="card">
            <div class="label">Balance</div>
            <div class="value">${formatCurrency(balance)}</div>
          </div>
        </div>

        <div class="grid">
          <div class="card">
            <div class="label">Savings Rate</div>
            <div class="value">${savingsRate.toFixed(1)}%</div>
          </div>

          <div class="card">
            <div class="label">Health Score</div>
            <div class="value">${healthScore.score}/100</div>
          </div>

          <div class="card">
            <div class="label">Status</div>
            <div class="value">${healthScore.label}</div>
          </div>
        </div>

        <h2>Top Spending Categories</h2>
        <table>
          <tr>
            <th>Category</th>
            <th style="text-align:right;">Amount</th>
          </tr>
          ${categoryRows}
        </table>

        <h2>Recent Transactions</h2>
        <table>
          <tr>
            <th>Description</th>
            <th>Category</th>
            <th>Type</th>
            <th style="text-align:right;">Amount</th>
          </tr>
          ${transactionRows}
        </table>

        <h2>Penny's Monthly Analysis</h2>
        <div class="analysis">
          ${escapeHtml(aiReport.response)}
        </div>

        <div class="footer">
          Budgetly Report · Generated automatically
        </div>
      </body>
    </html>
  `;

  if (Platform.OS === "web") {
    const printWindow = window.open("", "_blank");
  
    if (!printWindow) {
      throw new Error("Could not open report window.");
    }
  
    printWindow.document.open();
    printWindow.document.write(html);
    printWindow.document.close();
  
    setTimeout(() => {
      printWindow.focus();
      printWindow.print();
    }, 500);
  
    return null;
  }

  const { uri } = await Print.printToFileAsync({ html });

  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri);
  }

  return uri;
}